// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc0.MyRobot.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc0.MyRobot.subsystems.SlideTrain;
/**
 *
 */
public class arcadeDrive extends Command {

	private double m_speed;
    private double m_rotation;
    SlideTrain slideTrain = new SlideTrain();
    DifferentialDrive diffDrive = slideTrain.getDifferentialDrive();
    
    public arcadeDrive(double speed, double rotation) {

        m_speed = speed;
        m_rotation = rotation;
        SmartDashboard.putString("Differential Drive", "Speed: " + speed + " Rotation: " + rotation);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	diffDrive.arcadeDrive(m_speed, m_rotation, true);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
