// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.MyRobot.subsystems;

import org.usfirst.frc0.MyRobot.RobotMap;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

/**
 *
 */
public class SlideTrain extends Subsystem {

    private final WPI_TalonSRX talonL = RobotMap.slideTraintalonL;
    private final WPI_TalonSRX talonR = RobotMap.slideTraintalonR;
    private final DifferentialDrive differentialDrive = RobotMap.slideTrainDifferentialDrive;
    private final WPI_TalonSRX slider = RobotMap.slideTrainslider;
    private final WPI_TalonSRX _talonR = RobotMap.slideTrain_talonR;
    private final WPI_TalonSRX _talonL = RobotMap.slideTrain_talonL;

    
    @Override
    public void initDefaultCommand() {
    	// Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	_talonR.follow(talonR);
    	_talonL.follow(talonL);
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

	public DifferentialDrive getDifferentialDrive() {
		return differentialDrive;
	}

	public WPI_TalonSRX getSlider() {
		return slider;
	}

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

