// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.MyRobot;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static WPI_TalonSRX slideTraintalonL;
    public static WPI_TalonSRX slideTraintalonR;
    public static DifferentialDrive slideTrainDifferentialDrive;
    public static WPI_TalonSRX slideTrainslider;
    public static WPI_TalonSRX slideTrain_talonR;
    public static WPI_TalonSRX slideTrain_talonL;
    public static Servo clawclawServo;
    public static WPI_TalonSRX verticalLiftliftMotor;

    
    public static void init() {
        slideTraintalonL = new WPI_TalonSRX(0);
        slideTraintalonR = new WPI_TalonSRX(1);
                
        slideTrainDifferentialDrive = new DifferentialDrive(slideTraintalonL, slideTraintalonR);
        slideTrainDifferentialDrive.setSafetyEnabled(true);
        slideTrainDifferentialDrive.setExpiration(0.1);
        slideTrainDifferentialDrive.setMaxOutput(1.0);

        slideTrainslider = new WPI_TalonSRX(2);
                
        slideTrain_talonR = new WPI_TalonSRX(3);
        slideTrain_talonL = new WPI_TalonSRX(4);
        
        
        clawclawServo = new Servo(0);

        verticalLiftliftMotor = new WPI_TalonSRX(5);
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
